[phases.setup]
nixPkgs = ["bun", "openssl_3"]
aptPkgs = ["libssl3"]

[phases.install]
cmds = ["rm -rf node_modules bun.lock", "bun install"]

[phases.build]
cmds = ["bunx prisma generate"]

[start]
cmd = "bun run start"
